[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x", "php84", "php84Packages.composer", "php84Extensions.pdo_pgsql", "nginx"]

[phases.build]
cmds = ["rm -rf vendor", "composer install --no-dev --optimize-autoloader", "npm ci", "npm run build", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "php artisan migrate --force && (php artisan queue:work &) && nginx -g 'daemon off;'"
